version: "3.9"
services:
  app:
    #dockerfileがあるディレクトリを指定
    build: ./docker/php
    #ホスト側のディレクトリや名前付きvolumeをコンテナ側へマウントしたいときに指定(コンテナを削除しても永続的にデーターが残る)
    volumes:
      - ./src:/data
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data